controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

product_list:
    path: /api/products
    controller: App\Controller\ProductController::list
    methods: GET